recover:
	gcc -ggdb3 -O0 -Wunused-parameter -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow  -o recover.out recover.c 

clean:
	shred -fuzv recover && rm -r *.jpg
